#Issue KS-0 feat:Added Knowlg Search API and Job
Sunbird-Knowlg/knowlg-search pull request #1
Opened 2023-08-24 07:02 UTC by aimansharief

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Java 11, scala-2.11, play-2.7.2
* Hardware versions: 2 CPU/ 4GB RAM

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-29 09:58 UTC, maheshkumargangula requested changes
Remove the vscode or the intellij related files.

2023-08-29 09:58 UTC, maheshkumargangula commented on search-api/knowlg-search/search-service/app/utils/ApiId.scala
> +	final val APPLICATION_AUDIT_HISTORY = "api.search-service.audit_history.read"
```suggestion
	final val APPLICATION_AUDIT_HISTORY = "api.knowlg-search.audit-history.read"
```

2023-08-29 09:58 UTC, maheshkumargangula commented on search-job/jobs-core/src/main/scala/org/sunbird/job/cache/local/FrameworkMasterCategoryMap.scala
> +  val ttlMS = 100000l//Platform.getLong("master.category.cache.ttl", 10000l)
Why are we not using the configuration?

2023-08-30 05:41 UTC, aimansharief commented on search-api/knowlg-search/search-service/app/utils/ApiId.scala
> +	final val APPLICATION_AUDIT_HISTORY = "api.search-service.audit_history.read"
Updated AUDIT_HISTORY ApiId

2023-08-30 10:02 UTC, merged